# Generated by Django 3.2.2 on 2021-05-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutCompany', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maininfo',
            name='image',
            field=models.ImageField(blank=True, upload_to='about-us/main-info/%Y/%m/%d'),
        ),
    ]
