# Generated by Django 3.1.7 on 2021-03-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediabank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Пример работ(Видео)',
                'verbose_name_plural': 'Пример работ(Видео)',
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
