# Generated by Django 3.1.7 on 2021-03-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediabank', '0002_videomedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomedia',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
