# Generated by Django 3.1.7 on 2021-03-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediabank', '0003_photomedia_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomedia',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
