# Generated by Django 3.1.7 on 2021-03-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediabank', '0004_auto_20210330_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomedia',
            name='image',
            field=models.ImageField(blank=True, upload_to='mediabank/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='videomedia',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
