# Generated by Django 3.1.7 on 2021-04-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediabank', '0005_auto_20210330_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomedia',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
