# Generated by Django 3.1.7 on 2021-04-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'Оформить заказ(услуга)',
                'verbose_name_plural': 'Оформить заказ(услуга)',
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
